
package com.webservicesodispol;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WebServiceSodispol", targetNamespace = "http://WebServiceSodispol.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceSodispol {


    /**
     * 
     * @param matricula
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "datosEstudianteMatricula", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteMatricula")
    @ResponseWrapper(localName = "datosEstudianteMatriculaResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteMatriculaResponse")
    public List<Object> datosEstudianteMatricula(
        @WebParam(name = "matricula", targetNamespace = "")
        String matricula);

    /**
     * 
     * @param username
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "datosEstudianteUsername", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteUsername")
    @ResponseWrapper(localName = "datosEstudianteUsernameResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteUsernameResponse")
    public List<Object> datosEstudianteUsername(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param cedula
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "datosProfesionalCedula", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosProfesionalCedula")
    @ResponseWrapper(localName = "datosProfesionalCedulaResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosProfesionalCedulaResponse")
    public List<Object> datosProfesionalCedula(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula);

    /**
     * 
     * @param username
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "datosProfesionalUsername", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosProfesionalUsername")
    @ResponseWrapper(localName = "datosProfesionalUsernameResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosProfesionalUsernameResponse")
    public List<Object> datosProfesionalUsername(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @param cedula
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "datosEstudianteCedula", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteCedula")
    @ResponseWrapper(localName = "datosEstudianteCedulaResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.DatosEstudianteCedulaResponse")
    public List<Object> datosEstudianteCedula(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula);

    /**
     * 
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "tipoUsuario", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.TipoUsuario")
    @ResponseWrapper(localName = "tipoUsuarioResponse", targetNamespace = "http://WebServiceSodispol.com/", className = "com.webservicesodispol.TipoUsuarioResponse")
    public String tipoUsuario(
        @WebParam(name = "username", targetNamespace = "")
        String username);

}
