
package com.webservicesodispol;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WebServiceSodispol", targetNamespace = "http://WebServiceSodispol.com/", wsdlLocation = "file:/C:/Users/usuario/Desktop/SodispolWebService/SodispolSoftware/src/wsdl/WebServiceSodispol.wsdl")
public class WebServiceSodispol_Service
    extends Service
{

    private final static URL WEBSERVICESODISPOL_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.webservicesodispol.WebServiceSodispol_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.webservicesodispol.WebServiceSodispol_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/usuario/Desktop/SodispolWebService/SodispolSoftware/src/wsdl/WebServiceSodispol.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/usuario/Desktop/SodispolWebService/SodispolSoftware/src/wsdl/WebServiceSodispol.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WEBSERVICESODISPOL_WSDL_LOCATION = url;
    }

    public WebServiceSodispol_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceSodispol_Service() {
        super(WEBSERVICESODISPOL_WSDL_LOCATION, new QName("http://WebServiceSodispol.com/", "WebServiceSodispol"));
    }

    /**
     * 
     * @return
     *     returns WebServiceSodispol
     */
    @WebEndpoint(name = "WebServiceSodispolPort")
    public WebServiceSodispol getWebServiceSodispolPort() {
        return super.getPort(new QName("http://WebServiceSodispol.com/", "WebServiceSodispolPort"), WebServiceSodispol.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceSodispol
     */
    @WebEndpoint(name = "WebServiceSodispolPort")
    public WebServiceSodispol getWebServiceSodispolPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServiceSodispol.com/", "WebServiceSodispolPort"), WebServiceSodispol.class, features);
    }

}
