package com.sodispolSoftware.model;
// Generated 20-jul-2014 15:20:16 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Categoriapatologia generated by hbm2java
 */
public class Categoriapatologia  implements java.io.Serializable {


     private long idcategoria;
     private Boolean estadoborrado;
     private String descripcion;
     private Set<Patologia> patologias = new HashSet<Patologia>(0);

    public Categoriapatologia() {
    }

	
    public Categoriapatologia(long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public Categoriapatologia(long idcategoria, Boolean estadoborrado, String descripcion, Set<Patologia> patologias) {
       this.idcategoria = idcategoria;
       this.estadoborrado = estadoborrado;
       this.descripcion = descripcion;
       this.patologias = patologias;
    }
   
    public long getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(long idcategoria) {
        this.idcategoria = idcategoria;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Patologia> getPatologias() {
        return this.patologias;
    }
    
    public void setPatologias(Set<Patologia> patologias) {
        this.patologias = patologias;
    }




}


