package com.sodispolSoftware.model;
// Generated 20-jul-2014 15:20:16 by Hibernate Tools 3.6.0



/**
 * Categoriamedicinamedicina generated by hbm2java
 */
public class Categoriamedicinamedicina  implements java.io.Serializable {


     private long idcategoriamedicinamedicina;
     private Medicina medicina;
     private Categoriamedicina categoriamedicina;
     private Boolean estadoborrado;

    public Categoriamedicinamedicina() {
    }

    public Categoriamedicinamedicina(Boolean estadoborrado, Medicina medicina, Categoriamedicina categoriamedicina) {
        this.estadoborrado=estadoborrado;
        this.medicina = medicina;
        this.categoriamedicina = categoriamedicina;
    }
    
    public Categoriamedicinamedicina(long idcategoriamedicinamedicina, Medicina medicina, Categoriamedicina categoriamedicina) {
        this.idcategoriamedicinamedicina = idcategoriamedicinamedicina;
        this.medicina = medicina;
        this.categoriamedicina = categoriamedicina;
    }
    public Categoriamedicinamedicina(long idcategoriamedicinamedicina, Medicina medicina, Categoriamedicina categoriamedicina, Boolean estadoborrado) {
       this.idcategoriamedicinamedicina = idcategoriamedicinamedicina;
       this.medicina = medicina;
       this.categoriamedicina = categoriamedicina;
       this.estadoborrado = estadoborrado;
    }
   
    public long getIdcategoriamedicinamedicina() {
        return this.idcategoriamedicinamedicina;
    }
    
    public void setIdcategoriamedicinamedicina(long idcategoriamedicinamedicina) {
        this.idcategoriamedicinamedicina = idcategoriamedicinamedicina;
    }
    public Medicina getMedicina() {
        return this.medicina;
    }
    
    public void setMedicina(Medicina medicina) {
        this.medicina = medicina;
    }
    public Categoriamedicina getCategoriamedicina() {
        return this.categoriamedicina;
    }
    
    public void setCategoriamedicina(Categoriamedicina categoriamedicina) {
        this.categoriamedicina = categoriamedicina;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }




}


