package com.sodispolSoftware.model;
// Generated 18-jul-2014 18:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Doctor generated by hbm2java
 */
public class Doctor  implements java.io.Serializable,User {

     /*Atributos de la base de datos*/
     private long iddoctor;
     private Roleuser roleuser;
     private String username;
     private Boolean estadoborrado;
     private Set<Detalleabastecimiento> detalleabastecimientos = new HashSet<Detalleabastecimiento>(0);
     private Set<Citamedica> citamedicas = new HashSet<Citamedica>(0);
     private Set<Detallefichaestudiante> detallefichaestudiantes = new HashSet<Detallefichaestudiante>(0);

     
     /*Atributos de clase*/
     private String nombre1;
     private String nombre2;
     private String apellido1;
     private String apellido2;
     private String correo;
     private String especializacion;
     
    public Doctor() {
    }

	
    public Doctor(String username, Roleuser roleuser,Boolean estadoborrado) {
        this.username = username;
        this.roleuser = roleuser;
        this.estadoborrado = estadoborrado;
    }
    public Doctor(Roleuser roleuser, String username, Boolean estadoborrado, Set<Detalleabastecimiento> detalleabastecimientos, Set<Citamedica> citamedicas, Set<Detallefichaestudiante> detallefichaestudiantes) {
       
       this.roleuser = roleuser;
       this.username = username;
       this.estadoborrado = estadoborrado;
       this.detalleabastecimientos = detalleabastecimientos;
       this.citamedicas = citamedicas;
       this.detallefichaestudiantes = detallefichaestudiantes;
    }
   
    public long getIddoctor() {
        return this.iddoctor;
    }

    public void setIddoctor(long iddoctor) {
        this.iddoctor = iddoctor;
    }
    
    
     @Override
    public Roleuser getRoleuser() {
        return this.roleuser;
    }
    
    public void setRoleuser(Roleuser roleuser) {
        this.roleuser = roleuser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set<Detalleabastecimiento> getDetalleabastecimientos() {
        return this.detalleabastecimientos;
    }
    
    public void setDetalleabastecimientos(Set<Detalleabastecimiento> detalleabastecimientos) {
        this.detalleabastecimientos = detalleabastecimientos;
    }
    public Set<Citamedica> getCitamedicas() {
        return this.citamedicas;
    }
    
    public void setCitamedicas(Set<Citamedica> citamedicas) {
        this.citamedicas = citamedicas;
    }
    public Set<Detallefichaestudiante> getDetallefichaestudiantes() {
        return this.detallefichaestudiantes;
    }
    
    public void setDetallefichaestudiantes(Set<Detallefichaestudiante> detallefichaestudiantes) {
        this.detallefichaestudiantes = detallefichaestudiantes;
    }

    public String getNombre1() {
        return nombre1;
    }

    public void setNombre1(String nombre1) {
        this.nombre1 = nombre1;
    }

    public String getNombre2() {
        return nombre2;
    }

    public void setNombre2(String nombre2) {
        this.nombre2 = nombre2;
    }

    public String getApellido1() {
        return apellido1;
    }

    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return apellido2;
    }

    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getEspecializacion() {
        return especializacion;
    }

    public void setEspecializacion(String especializacion) {
        this.especializacion = especializacion;
    }

     @Override
    public String toString(){
        return this.nombre1 + " "+ this.apellido1;
    }


}


