package com.sodispolSoftware.model;
// Generated 18-jul-2014 18:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Enfermero generated by hbm2java
 */
public class Enfermero  implements java.io.Serializable {


     private long idenfermero;
     private Roleuser roleuser;
     private String username;
     private Boolean estadoborrado;
     private Set<Detalleabastecimiento> detalleabastecimientos = new HashSet<Detalleabastecimiento>(0);

    public Enfermero() {
    }

	
    public Enfermero(long idenfermero, Roleuser roleuser) {
        this.idenfermero = idenfermero;
        this.roleuser = roleuser;
    }
    public Enfermero(long idenfermero, Roleuser roleuser, String username, Boolean estadoborrado, Set<Detalleabastecimiento> detalleabastecimientos) {
       this.idenfermero = idenfermero;
       this.roleuser = roleuser;
       this.username = username;
       this.estadoborrado = estadoborrado;
       this.detalleabastecimientos = detalleabastecimientos;
    }
   
    public long getIdenfermero() {
        return this.idenfermero;
    }
    
    public void setIdenfermero(long idenfermero) {
        this.idenfermero = idenfermero;
    }
    public Roleuser getRoleuser() {
        return this.roleuser;
    }
    
    public void setRoleuser(Roleuser roleuser) {
        this.roleuser = roleuser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set<Detalleabastecimiento> getDetalleabastecimientos() {
        return this.detalleabastecimientos;
    }
    
    public void setDetalleabastecimientos(Set<Detalleabastecimiento> detalleabastecimientos) {
        this.detalleabastecimientos = detalleabastecimientos;
    }




}


