package com.sodispolSoftware.model;
// Generated 18-jul-2014 18:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private long idestudiante;
     private Roleuser roleuser;
     private String username;
     private String direccion;
     private String estadocivil;
     private String telefono;
     private Boolean estadoborrado;
     private Set<Citamedica> citamedicas = new HashSet<Citamedica>(0);
     private Set<Fichamedicaestudiante> fichamedicaestudiantes = new HashSet<Fichamedicaestudiante>(0);

    public Estudiante() {
    }

	
    public Estudiante(long idestudiante, Roleuser roleuser) {
        this.idestudiante = idestudiante;
        this.roleuser = roleuser;
    }
    public Estudiante(long idestudiante, Roleuser roleuser, String username, String direccion, String estadocivil, String telefono, Boolean estadoborrado, Set<Citamedica> citamedicas, Set<Fichamedicaestudiante> fichamedicaestudiantes) {
       this.idestudiante = idestudiante;
       this.roleuser = roleuser;
       this.username = username;
       this.direccion = direccion;
       this.estadocivil = estadocivil;
       this.telefono = telefono;
       this.estadoborrado = estadoborrado;
       this.citamedicas = citamedicas;
       this.fichamedicaestudiantes = fichamedicaestudiantes;
    }
   
    public long getIdestudiante() {
        return this.idestudiante;
    }
    
    public void setIdestudiante(long idestudiante) {
        this.idestudiante = idestudiante;
    }
    public Roleuser getRoleuser() {
        return this.roleuser;
    }
    
    public void setRoleuser(Roleuser roleuser) {
        this.roleuser = roleuser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEstadocivil() {
        return this.estadocivil;
    }
    
    public void setEstadocivil(String estadocivil) {
        this.estadocivil = estadocivil;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set<Citamedica> getCitamedicas() {
        return this.citamedicas;
    }
    
    public void setCitamedicas(Set<Citamedica> citamedicas) {
        this.citamedicas = citamedicas;
    }
    public Set<Fichamedicaestudiante> getFichamedicaestudiantes() {
        return this.fichamedicaestudiantes;
    }
    
    public void setFichamedicaestudiantes(Set<Fichamedicaestudiante> fichamedicaestudiantes) {
        this.fichamedicaestudiantes = fichamedicaestudiantes;
    }




}


