package com.sodispolSoftware.model;
// Generated 20-jul-2014 15:20:16 by Hibernate Tools 3.6.0


import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Medicinaepecifica generated by hbm2java
 */
public class Medicinaepecifica  implements java.io.Serializable {


     private long idmedicinaespecifica;
     private Medicina medicina;
     private Integer unidadesdisponibles;
     private Calendar fechacaducidad;
     private Boolean estadocaducado;
     private Boolean estadoborrado;
     private Set<Receta> recetas = new HashSet<Receta>(0);

    public Medicinaepecifica() {
    }

	
    public Medicinaepecifica(long idmedicinaespecifica, Medicina medicina) {
        this.idmedicinaespecifica = idmedicinaespecifica;
        this.medicina = medicina;
    }
    public Medicinaepecifica(Integer unidadesdisponibles, Boolean estadocaducado, Boolean estadoborrado, Medicina medicina, Calendar fechacaducidad ) {
        this.unidadesdisponibles=unidadesdisponibles;
        this.estadocaducado=estadocaducado;
        this.estadoborrado=estadoborrado;
        this.medicina=medicina;
        this.fechacaducidad=fechacaducidad;
    }
    public Medicinaepecifica(long idmedicinaespecifica, Medicina medicina, Integer unidadesdisponibles, Calendar fechacaducidad, Boolean estadocaducado, Boolean estadoborrado, Set<Receta> recetas) {
       this.idmedicinaespecifica = idmedicinaespecifica;
       this.medicina = medicina;
       this.unidadesdisponibles = unidadesdisponibles;
       this.fechacaducidad = fechacaducidad;
       this.estadocaducado = estadocaducado;
       this.estadoborrado = estadoborrado;
       this.recetas = recetas;
    }
   
    public long getIdmedicinaespecifica() {
        return this.idmedicinaespecifica;
    }
    
    public void setIdmedicinaespecifica(long idmedicinaespecifica) {
        this.idmedicinaespecifica = idmedicinaespecifica;
    }
    public Medicina getMedicina() {
        return this.medicina;
    }
    
    public void setMedicina(Medicina medicina) {
        this.medicina = medicina;
    }
    public Integer getUnidadesdisponibles() {
        return this.unidadesdisponibles;
    }
    
    public void setUnidadesdisponibles(Integer unidadesdisponibles) {
        this.unidadesdisponibles = unidadesdisponibles;
    }
    public Calendar getFechacaducidad() {
        return this.fechacaducidad;
    }
    
    public void setFechacaducidad(Calendar fechacaducidad) {
        this.fechacaducidad = fechacaducidad;
    }
    public Boolean getEstadocaducado() {
        return this.estadocaducado;
    }
    
    public void setEstadocaducado(Boolean estadocaducado) {
        this.estadocaducado = estadocaducado;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set<Receta> getRecetas() {
        return this.recetas;
    }
    
    public void setRecetas(Set<Receta> recetas) {
        this.recetas = recetas;
    }




}


