package com.sodispolSoftware.model;
// Generated 20-jul-2014 15:20:16 by Hibernate Tools 3.6.0



/**
 * Patologiadetalleficha generated by hbm2java
 */
public class Patologiadetalleficha  implements java.io.Serializable {


     private long idpatogogiaficha;
     private Detallefichaestudiante detallefichaestudiante;
     private Patologia patologia;
     private Boolean estadoborrado;

    public Patologiadetalleficha() {
    }

	
    public Patologiadetalleficha(long idpatogogiaficha, Detallefichaestudiante detallefichaestudiante, Patologia patologia) {
        this.idpatogogiaficha = idpatogogiaficha;
        this.detallefichaestudiante = detallefichaestudiante;
        this.patologia = patologia;
    }
    public Patologiadetalleficha(long idpatogogiaficha, Detallefichaestudiante detallefichaestudiante, Patologia patologia, Boolean estadoborrado) {
       this.idpatogogiaficha = idpatogogiaficha;
       this.detallefichaestudiante = detallefichaestudiante;
       this.patologia = patologia;
       this.estadoborrado = estadoborrado;
    }
   
    public long getIdpatogogiaficha() {
        return this.idpatogogiaficha;
    }
    
    public void setIdpatogogiaficha(long idpatogogiaficha) {
        this.idpatogogiaficha = idpatogogiaficha;
    }
    public Detallefichaestudiante getDetallefichaestudiante() {
        return this.detallefichaestudiante;
    }
    
    public void setDetallefichaestudiante(Detallefichaestudiante detallefichaestudiante) {
        this.detallefichaestudiante = detallefichaestudiante;
    }
    public Patologia getPatologia() {
        return this.patologia;
    }
    
    public void setPatologia(Patologia patologia) {
        this.patologia = patologia;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }




}


