package com.sodispolSoftware.model;
// Generated 18-jul-2014 18:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Patologia generated by hbm2java
 */
public class Patologia  implements java.io.Serializable {


     private long idpatologia;
     private Categoriapatologia categoriapatologia;
     private String nombre;
     private String descripcion;
     private Boolean estadoborrado;
     private Set<Patologiadetalleficha> patologiadetallefichas = new HashSet<Patologiadetalleficha>(0);

    public Patologia() {
    }

	
    public Patologia(long idpatologia, Categoriapatologia categoriapatologia) {
        this.idpatologia = idpatologia;
        this.categoriapatologia = categoriapatologia;
    }
    public Patologia(long idpatologia, Categoriapatologia categoriapatologia, String nombre, String descripcion, Boolean estadoborrado, Set<Patologiadetalleficha> patologiadetallefichas) {
       this.idpatologia = idpatologia;
       this.categoriapatologia = categoriapatologia;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estadoborrado = estadoborrado;
       this.patologiadetallefichas = patologiadetallefichas;
    }
   
    public long getIdpatologia() {
        return this.idpatologia;
    }
    
    public void setIdpatologia(long idpatologia) {
        this.idpatologia = idpatologia;
    }
    public Categoriapatologia getCategoriapatologia() {
        return this.categoriapatologia;
    }
    
    public void setCategoriapatologia(Categoriapatologia categoriapatologia) {
        this.categoriapatologia = categoriapatologia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstadoborrado() {
        return this.estadoborrado;
    }
    
    public void setEstadoborrado(Boolean estadoborrado) {
        this.estadoborrado = estadoborrado;
    }
    public Set<Patologiadetalleficha> getPatologiadetallefichas() {
        return this.patologiadetallefichas;
    }
    
    public void setPatologiadetallefichas(Set<Patologiadetalleficha> patologiadetallefichas) {
        this.patologiadetallefichas = patologiadetallefichas;
    }




}


