package com.sodispolSoftware.model;
// Generated 18-jul-2014 18:32:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Roleuser generated by hbm2java
 */
public class Roleuser  implements java.io.Serializable {


     private long idroleuser;
     private String descripcion;
     private Set<Enfermero> enfermeros = new HashSet<Enfermero>(0);
     private Set<Doctor> doctors = new HashSet<Doctor>(0);
     private Set<Estudiante> estudiantes = new HashSet<Estudiante>(0);

    public Roleuser() {
    }

	
    public Roleuser(long idroleuser) {
        this.idroleuser = idroleuser;
    }
    public Roleuser(long idroleuser, String descripcion, Set<Enfermero> enfermeros, Set<Doctor> doctors, Set<Estudiante> estudiantes) {
       this.idroleuser = idroleuser;
       this.descripcion = descripcion;
       this.enfermeros = enfermeros;
       this.doctors = doctors;
       this.estudiantes = estudiantes;
    }
   
    public long getIdroleuser() {
        return this.idroleuser;
    }
    
    public void setIdroleuser(long idroleuser) {
        this.idroleuser = idroleuser;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Enfermero> getEnfermeros() {
        return this.enfermeros;
    }
    
    public void setEnfermeros(Set<Enfermero> enfermeros) {
        this.enfermeros = enfermeros;
    }
    public Set<Doctor> getDoctors() {
        return this.doctors;
    }
    
    public void setDoctors(Set<Doctor> doctors) {
        this.doctors = doctors;
    }
    public Set<Estudiante> getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set<Estudiante> estudiantes) {
        this.estudiantes = estudiantes;
    }




}


